# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI (build and test)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    - name: Test with coverage
      run: dotnet test --configuration Release --collect:"XPlat Code Coverage"

    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura'

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coveragereport